# Generated by Django 4.2.29 on 2026-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='golfscore',
            options={'ordering': ['-played_at', '-submitted_at']},
        ),
        migrations.AddField(
            model_name='golfscore',
            name='played_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
