# Generated by Django 4.2.29 on 2026-03-24 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('total_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('jackpot_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('jackpot_rolled_over', models.BooleanField(default=False)),
                ('winning_numbers', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrawWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField()),
                ('prize_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_proof', 'Pending Proof'), ('proof_submitted', 'Proof Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending_proof', max_length=20)),
                ('proof_screenshot_url', models.URLField(blank=True)),
                ('proof_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='draws.drawround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrawEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField()),
                ('matches', models.PositiveIntegerField(default=0)),
                ('tier_won', models.PositiveIntegerField(blank=True, null=True)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='draws.drawround')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('draw', 'user')},
            },
        ),
    ]
