# Generated by Django 4.2.29 on 2026-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draws', '0002_adminauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawround',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drawround',
            name='logic_type',
            field=models.CharField(choices=[('random', 'Random (Lottery)'), ('weighted', 'Algorithmic (Weighted)')], default='random', max_length=20),
        ),
    ]
