# Generated by Django 4.2.29 on 2026-03-27 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charities', '0002_charity_created_at_charity_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='managed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_charity', to=settings.AUTH_USER_MODEL),
        ),
    ]
