# Generated by Django 4.2.29 on 2026-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_charity_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='charities/logos/'),
        ),
    ]
