# Generated by Django 4.2.29 on 2026-03-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_charity_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
