# Generated by Django 4.2.29 on 2026-03-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0005_charity_contact_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={},
        ),
        migrations.CreateModel(
            name='CharityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='charities/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_banner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='charities.charity')),
            ],
        ),
        migrations.CreateModel(
            name='CharityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='charities/events/')),
                ('link_url', models.URLField(blank=True, help_text='Link to external event page or registration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='charities.charity')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
