# Generated by Django 4.2.29 on 2026-03-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('member', 'Member'), ('organization', 'Organization'), ('admin', 'Admin')], default='member', max_length=20),
        ),
    ]
